[project]
name = "django-basicapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.4",
    "django-browser-reload>=1.18.0",
    "django-tailwind>=4.2.0",
    "pillow>=11.3.0",
]
